### ISSUE TITLE
Integration of CRAVAT and CIViC

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-meeting#32]
There is interest in integration of CRAVAT and CIViC (possibly bi-directional?).  In what specific ways?  To be discussed with the Karchin Lab (https://github.com/KarchinLab).

**Comment by mryaninsilico** [comment]
Possible items for CRAVAT / CIVIC hackathon:

- implement a new Open-CRAVAT (https://github.com/KarchinLab/open-cravat/wiki) annotator for integrating CIVIC information into CRAVAT variant processing
(maybe make this a new kind of annotator that uses a web service to get data rather than a pre-compute so CIVIC data will always be fresh)

- implement a Open-CRAVAT visualization widget for CIVIC results including a link-out to the CIVIC site for variant annotation details

- Add a linkout from the CIVIC variant details page to the CRAVAT website Single Variant Page (example: http://www.cravat.us/CRAVAT/variant.html?variant=chr21_34859485_+_C_T)

**Comment by kmoad** [comment]
https://drive.google.com/file/d/11kYlo_Es9rghYSYCQVdSdV9ooUMU5Z8V/view?usp=sharing
